version: '3'
services:
  nginx:
    image: nginx
    container_name: ollama-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx-docker/conf:/etc/nginx:ro
      - ./nginx-docker/logs:/var/log/nginx
    restart: always
